FROM python:3.9.16-alpine3.17
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
ENV FLASK_RUN_PORT=8080
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
